### PR TITLE
SENML JSON integration test

### PR DESCRIPTION
**Pull request by mgdlkundera**
SENML JSON test with reference to conversation:
https://github.com/eclipse-leshan/leshan/issues/1554

### CODE REVIEW

**Comment by mgdlkundera** [comment]
In this structure we have 2 bn, so if we don't implement this test our leshan client will not work with leshan server in case of some future changes in code. We want to be sure that this data structure  will be supported in the future that is why we should add this dedicated test.

**Comment by sbernard31** [comment]
> We want to be sure that this data structure will be supported in the future 

I understand.

> In this structure we have 2 bn, 

I'm not sure what you have in mind but there are tests in `LwM2mNodeDecoderTest` with 2 `bn`. 

So please, could you have another quick look at [existing tests](https://github.com/eclipse-leshan/leshan/blob/3a1adfea5c06c23f0a73e5339f71a76bfca0e58e/leshan-core/src/test/java/org/eclipse/leshan/core/node/codec/LwM2mNodeDecoderTest.java#L896-L1369)

Just to be sure we don't add useless tests.

Then If after looking at this, you still think that current tests are not enough, then we can add your tests. :slightly_smiling_face:

**Comment by mgdlkundera** [comment]
I looked through the existing tests again and there is no test with this structure, so could we add my test? 🙂

**Comment by sbernard31** [comment]
OK, so I integrated this in `master` (commit 777d2ed4d63d30ebfc483e45b61ae74ce466c61e)

I did some little changes : 
- I moved the test with other senml tests
- I renamed it
- I get node by timestamp (to ensure timestamp are well decoded)
- I rename commit title to refer to original issue : https://github.com/eclipse-leshan/leshan/issues/1554

**Comment by mgdlkundera** [comment]
Tkank you 🙂

**Pull request closed without merging**
