### PR TITLE
Implementation of observe on root.

### PR DESCRIPTION
**Pull request by mgdlkundera**
This commit include:
* implementation of observe operation on root
* test of observe on root

### CODE REVIEW

**Comment by sbernard31** [comment]
I looked at it but didn't test it yet. 
At first sight, this sounds good. :+1: 

Only little detail maybe we can change the test a little by adding : 
 - do a modification  which will a notification
 - check the notification content is OK. 
 
 To trigger the notification you can either  : 
  - send a WriteRequest.
 -  or Look at TestObject (Id 3442), you can use **leshan-server-demo** and **leshan-client-demo** to see how it works
 (and see resource /3442/0/0, /3442/0/1, /3442/0/2)

Note that we are currently in code freeze for the 2.0.0-M14 release so we will be able to integrate it in `master` only after the release. :slightly_smiling_face:

**Comment by sbernard31** [comment]
@mgdlkundera do you plan to modify the test ? If not let me know, so I do it :slightly_smiling_face:

**Comment by sbernard31** [comment]
Ok I will try to work on this tomorrow.

**Comment by sbernard31** [comment]
This is done and integrated in `master` commit (ab645dd10ab5e9c9d982e22621ad92cb3a2e0327)

I finally decide to go with a "simple write" to trigger the notification.
I also fixed an issue in test where you used `ObserveRequest` instead of `ReadRequest` : 
https://github.com/eclipse-leshan/leshan/blob/55f008fa838bc05d4b2c8556dee54ba23bbd087e/leshan-integration-tests/src/test/java/org/eclipse/leshan/integration/tests/observe/ObserveCompositeTest.java#L302-L303

If you are curious, do not hesitate to look at [the code](https://github.com/eclipse-leshan/leshan/blob/ab645dd10ab5e9c9d982e22621ad92cb3a2e0327/leshan-integration-tests/src/test/java/org/eclipse/leshan/integration/tests/observe/ObserveCompositeTest.java#L260-L324)

@mgdlkundera  Thx for you contribution :pray:

**Comment by mgdlkundera** [comment]
I'll look at the code. Thank you for your help.

**Pull request closed without merging**
