### PR TITLE
Add configuration to enable to update registration on send operation. 

### PR DESCRIPTION
**Pull request by sbernard31**
See #1421 for more details.

### CODE REVIEW

**Review by Warmek — APPROVED** [review]
👍

**Comment by sbernard31** [comment]
@JaroslawLegierski following discussion at https://github.com/eclipse-leshan/leshan/issues/1421

Do you think we should integrate this in `master` ?

**Comment by JaroslawLegierski** [comment]
> @JaroslawLegierski following discussion at #1421
> 
> Do you think we should integrate this in `master` ?

I think that this feature could be useful in the future (e.g. used together also with updateRegistrationOnNotify).

**Comment by sbernard31** [comment]
> I think that this feature could be useful in the future (e.g. used together also with updateRegistrationOnNotify).

Ok I will integrate it in `master`, I hope I will not regret it later as this is not really LWM2M compliant.

**Pull request merged**
